### ISSUE TITLE
intranet_mtu_uplink property on resource "vmc_sddc" does not update when deployment_type = "DEFAULT"

### ISSUE THREAD

**Issue by AdrianBegg** [vmware/terraform-provider-vmc#100]
Hi,

I have hit a possible defect with the  vmc_sddc resource intranet_mtu_uplink property for SDDCs built with the deployment_type = "DEFAULT". 

**Summary**: When setting intranet_mtu_uplink property to any non-default value (e.g. 8500) against a vmc_sddc resource where the "deployment_type" is set to "DEFAULT" , during the `terraform apply` after the SDDC is built terraform detects the drift and reports that the update successfully applied:
```
vmc_sddc.SDDC["MTU-Test-Default"]: Modifying... [id=f1c8b26d-7cab-4afd-92da-aa3edf8e4343]
vmc_sddc.SDDC["MTU-Test-Default"]: Modifications complete after 9s [id=f1c8b26d-7cab-4afd-92da-aa3edf8e4343]
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
When checking the SDDC however the MTU setting not being adjusted from the default value of 1500. This **does not** occur for "deployment_type" = 1NODE (when a single node cluster is set the update is as expected). I have tested several cases and the behavior appears to be consistent that for 1NODE the setting is always updated as expected however for a default Cluster (3-Node+) the change is never taking effect.

**Provider Versions Tested**: 1.5.0, 1.5.1
**Terraform Versions**: 0.14.5
**VMC Version**:  1.13 (1.13.0.1)

Example resource block for a default SDDC (where the update is not functioning):
```
resource "vmc_sddc" "MTU_Standard" {
  provider_type      = "AWS"
  sddc_name          = "MTU-Test-1NODE"
  deployment_type    = "SingleAZ"
  sddc_type          = "DEFAULT"
  size               = "MEDIUM"
  host_instance_type = "I3_METAL"
  num_host           = 6
  region             = "EU_CENTRAL_1"
  vpc_cidr           = ...
  vxlan_subnet       = ...

  delay_account_link  = false
  skip_creating_vxlan = false
  sso_domain          = "vmc.local"

  edrs_policy_type = "cost"
  enable_edrs      = true
  min_hosts        = 6
  max_hosts        = 10

  account_link_sddc_config {
    customer_subnet_ids  = ...
    connected_account_id = data.vmc_connected_accounts.var_aws_accounts.id
  }

  intranet_mtu_uplink = 8500

  microsoft_licensing_config {
    mssql_licensing   = "DISABLED"
    windows_licensing = "DISABLED"
  }
}
```

Example resource block for a single node (where the update is functioning):
```
resource "vmc_sddc" "MTU_1NODE" {
  provider_type      = "AWS"
  sddc_name          = "MTU-Test-1NODE"
  deployment_type    = "SingleAZ"
  sddc_type          = "1NODE"
  size               = "MEDIUM"
  host_instance_type = "I3_METAL"
  num_host           = 6
  region             = "EU_CENTRAL_1"
  vpc_cidr           = ...
  vxlan_subnet       = ...

  delay_account_link  = false
  skip_creating_vxlan = false
  sso_domain          = "vmc.local"

  edrs_policy_type = "cost"
  enable_edrs      = true
  min_hosts        = 6
  max_hosts        = 10

  account_link_sddc_config {
    customer_subnet_ids  = ...
    connected_account_id = data.vmc_connected_accounts.var_aws_accounts.id
  }

  intranet_mtu_uplink = 8500

  microsoft_licensing_config {
    mssql_licensing   = "DISABLED"
    windows_licensing = "DISABLED"
  }
}
```

**Comment by shylasrinivas** [comment]
@AdrianBegg thank you for reporting the issue, will take a look.
