### ISSUE TITLE
Using AWS specific region naming causes SDDC replacement

### ISSUE THREAD

**Issue by uprightvinyl** [vmware/terraform-provider-vmc#102]
### Expected Behavior
I can create a vmc_sddc using AWS specific region naming (e.g. eu-west-1).

### Current Behavior
The initial `apply` is successful, but a subsequent `plan` shows that the resource needs to be replaced, due to region naming changing from the VMware specific naming, which has been recorded in the state file, to the AWS specific naming, which is in the terraform configuration. No changes have been made to the configuration between the first `apply` and the subsequent `plan`.

### Possible Solution
If VMware specific naming is used in the terraform configuration, this issue does not occur. However, this means maintaining two different variables, or a map, when also using the AWS region naming in other places of the configuration, such as an AWS VPC.

The best solution would be to be able to use both VMC and AWS region naming, as shown in the documentation. I'm also fairly sure this has not happened with previous versions of the provider, although I have not done sufficient testing to confirm which version introduces this bug.

### Steps to Reproduce

```
resource "vmc_sddc" "sddc_a" {
  sddc_name           = "SDDC A"
  vpc_cidr            = "10.2.0.0/16"
  num_host            = 1
  provider_type       = "AWS"
  region              = "eu-west-1"
  delay_account_link  = false
  skip_creating_vxlan = true
  sso_domain          = "vmc.local"
  deployment_type     = "SingleAZ"
  sddc_type           = "1NODE"

  account_link_sddc_config {
    customer_subnet_ids  = [aws_subnet.sddc_a_connected_vpc_subnet[0].id]
    connected_account_id = data.vmc_connected_accounts.vmc_connected_account.id
  }
```

1. Run `terraform apply` with the above resource
1. Run `terraform plan`
1. The following is shown:

```  
# vmc_sddc.sddc_a must be replaced
-/+ resource "vmc_sddc" "sddc_a" {
....
      ~ region                 = "EU_WEST_1" -> "eu-west-1" # forces replacement
....
```

### Context (Environment)
```
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/aws v3.27.0
+ provider registry.terraform.io/terraform-providers/vmc v1.5.1
```

**Comment by vanditsmehta** [comment]
Please use the region field as described in this example: https://github.com/vmware/terraform-provider-vmc/blob/f92e5202f17c7593bda4ff345e90ba066d2f3912/examples/sddc/main.tf#L15
