### ISSUE TITLE
Feature Request: content library resource/data handlers

### ISSUE THREAD

**Issue by StorageMatt** [vmware/terraform-provider-vmc#103]
One for the 'nice to have' list; a resource handler for the creation of content libraries with datastore selection and primary or secondary designation. Obviously then it'd need datastore[_cluster] selection, a publish switch for primary and a force_sync option if secondary is selected.
The data handler would assist with the downstream codebase(s) for customers looking for templates etc.

**Comment by tenthirtyam** [comment]
Why not use the Terraform Provider for vSphere for this operation?

https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/content_library

Ryan

**Comment by dimitarproynov** [comment]
The VMC service has no Content Library APIs, so after deploying an SDDC one should use the Terraform Provider for vSphere to import the VC from the SDDC and execute any content library APIs on it.
