### ISSUE TITLE
SDDC deployment

### ISSUE THREAD

**Issue by xfirestyle2k** [vmware/terraform-provider-vmc#110]
empty non-retryable error received. This is a bug with the Terraform provider and should be reported as a GitHub issue in the provider repository.
│
│   with vmc_sddc.sddc_3,
│   on main.tf line 18, in resource "vmc_sddc" "sddc_3":
│   18: resource "vmc_sddc" "sddc_3" {
│
╵

Hi, getting following error when I deploy a new SDDC.
However, deployment was successful and the SDDC is available. 

terraform -version
Terraform v0.15.3
on windows_amd64
+ provider registry.terraform.io/terraform-providers/vmc v1.7.0

Your version of Terraform is out of date! The latest version
is 1.0.4. You can update by downloading from https://www.terraform.io/downloads.html
PS C:\Users\thoma\OneDrive - VMware, Inc\Github\SDDC-deployment-test-environment>

**Comment by sumitAgrawal007** [comment]
Can you update your terraform version and try pulling the latest terraform-provider-vmc and let us know.

**Comment by xfirestyle2k** [comment]
Hi Sumit, 
same error:
│ Error: empty non-retryable error received. This is a bug with the Terraform provider and should be reported as a GitHub issue in the provider repository.

 t --version
Terraform v1.0.4
on windows_amd64
+ provider registry.terraform.io/terraform-providers/vmc v1.7.0

**Comment by xfirestyle2k** [comment]
Hi Sumit,
it's me again. I am also getting following error from time to time..

**Comment by xfirestyle2k** [comment]
t apply
╷
│ Error:  Expected a value of type 'ListValue', but received a value of type '*data.StructValue'
│
│   with data.vmc_connected_accounts.my_accounts,
│   on main.tf line 9, in data "vmc_connected_accounts" "my_accounts":
│    9: data "vmc_connected_accounts" "my_accounts" {

Sorry.. I misclicked..

**Comment by pcradduc** [comment]
I am having the same issue: 

│ Error: empty non-retryable error received. This is a bug with the Terraform provider and should be reported as a GitHub issue in the provider repository.
│
│   with vmc_sddc.vmc_on_aws_sddc,
│   on SDDC.tf line 1, in resource "vmc_sddc" "vmc_on_aws_sddc":
│    1: resource "vmc_sddc" "vmc_on_aws_sddc" {
│

It did however deploy the SDDC, but when I ran plan the SDDC was marked as tainted. TF want to replace the SDDC now.

**Comment by jbianquetti-nami** [comment]
Same for me: 
- SDDC is deployed but apply fails.  
- TF wants to replace SDDC because it's tainted

**Comment by mnemesh-pivotal** [comment]
Previously using version 1.5.1 we were able to deploy our SDDC.  Due to a problem we had to redeploy our SDDC.  Using 1.7.0 we received  this error.  

> │ Error: empty non-retryable error received. This is a bug with the Terraform provider and should be reported as a GitHub issue in the provider repository.
> │ 
> │   with vmc_sddc.sddc_1,
> │   on vmc-aws-sddc.tf line 36, in resource "vmc_sddc" "sddc_1":
> │   36: resource "vmc_sddc" "sddc_1" {
> │ 

We got the same error trying to destroy our SDDC.  After returning to 1.5.1 we were able to complete the destroy.  We are now deploying using 1.5.1 and will report back if there any any further issues.

**Comment by riperez123** [comment]
Any update on this issue? I have hit this bug as well

**Comment by samirshaik** [comment]
```
$ terraform --version
Terraform v1.0.11
on windows_amd64
+ provider registry.terraform.io/vmware/vmc v1.8.0
```

**When creating SDDC we get following error, SDDC gets created but state file marks the status as "tainted".**
```
│ Error: error creating SDDC : com.vmware.vapi.std.errors.service_unavailable
│
│   with vmc_sddc.sddc_1,
│   on main.tf line 18, in resource "vmc_sddc" "sddc_1":
│   18: resource "vmc_sddc" "sddc_1" {

```

**When destroying SDDC we get following error, but SDDC gets deleted.**

` Error: error deleting SDDC xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx: com.vmware.vapi.std.errors.service_unavailable`

**Find below snippet from logs**
`2021-12-09T06:08:17.516-0500 [INFO]  provider.terraform-provider-vmc_v1.8.0.exe: 2021/12/09 06:08:17 Error completing client request 'Get "https://vmc.vmware.com/vmc/api/orgs/xxxxxxxx-f67a-4256-92b6-xxxxxxxxxxxx/tasks/xxxxxxxx-6ee8-44f8-9425-xxxxxxxxxxxx": read tcp 192.168.0.221:58333->52.41.161.116:443: wsarecv: An existing connection was forcibly closed by the remote host.': timestamp=2021-12-09T06:08:17.516-0500`

**Comment by samirshaik** [comment]
@sumitAgrawal007 : Any updates on this? Are you still going to look into this issue?

**Comment by vanditsmehta** [comment]
@samirshaik , We are working on the issue and try get the fix out at the earliest.

**Comment by samirshaik** [comment]
Does this have anything to do with retryContext having default timeout of 500 ms? From our initial analysis it looked like VMware APIs are being called more often than permitted and that 500 ms cannot even be override. We haven't done deep dive, so cannot say for sure.
