### ISSUE TITLE
After Initial Deployment SDDC Replacement is Forced

### ISSUE THREAD

**Issue by pcradduc** [vmware/terraform-provider-vmc#111]
This is the same issue reported here in issue #102 (https://github.com/vmware/terraform-provider-vmc/issues/102) except I am using version 1.7.

**Expected Behavior**
I can create a vmc_sddc using AWS specific region naming example us-west-2 and then make incremental updates

**Current Behavior**
The initial apply is successful, but  after that plan and apply shows that the resource needs to be replaced, 

The error is pointing to ~ region = "US_WEST_2" -> "us-west-2" # forces replacement

**Steps to Reproduce:**

_resource "vmc_sddc" "vmc_on_aws_sddc" {
  count                   = var.vmconaws ? 1 : 0
  sddc_name          = var.sddc_name
  vpc_cidr               = var.sddc_mgmt_cidr
  num_host            = 1
  provider_type       = "AWS"
  region                  = "us-west-2"
  size                = "MEDIUM"
  delay_account_link  = false
  skip_creating_vxlan = true
  vxlan_subnet        = var.vxlan_cidr
  sso_domain          = "vmc.local"
  deployment_type     = "SingleAZ"
  sddc_type           = "1NODE"
  host_instance_type = "I3_METAL"

  account_link_sddc_config {
    customer_subnet_ids  = [aws_subnet.Private_Subnet_1_AZ_2.id]
    connected_account_id = data.vmc_connected_accounts.my_accounts.id
  }

  timeouts {
    create = "300m"
    update = "300m"
    delete = "180m"
  }

  lifecycle {
    ignore_changes = [
      edrs_policy_type,
      max_hosts,
      min_hosts,
    ]
  }

  microsoft_licensing_config {
   mssql_licensing = "DISABLED"
   windows_licensing = "DISABLED"
  }
}_

Run terraform apply with the above resource
Run terraform plan

**vmc_sddc.sddc_test must be replaced
-/+ resource "vmc_sddc" "sddc_test" {
....
~ region                 = "US_WEST_2" -> "us-west-2" # forces replacement
....**

**Context (Environment)**
Terraform v1.0.3
on windows_386
+ provider registry.terraform.io/hashicorp/aws v3.56.0
+ provider registry.terraform.io/vmware/vmc v1.7.0

**Comment by vanditsmehta** [comment]
Please use region field as described in this sample file: https://github.com/vmware/terraform-provider-vmc/blob/f92e5202f17c7593bda4ff345e90ba066d2f3912/examples/sddc/main.tf#L15
