### ISSUE TITLE
Lack of multi-cluster SDDC support in "resourceSddcUpdate" function

### ISSUE THREAD

**Issue by Nick-Andreev** [vmware/terraform-provider-vmc#113]
Correct me if I'm wrong, but judging by this code in the provider, it seems that the `resourceSddcUpdate` function assumes there's only one cluster in SDDC:

https://github.com/vmware/terraform-provider-vmc/blob/7a0699b1f34909795b53da8af7eb63a652fa4e11/vmc/resource_vmc_sddc.go#L577

When number of hosts in SDDC changes, `resourceSddcUpdate` function attempts to add or remove hosts to bring it back into compliance. However, the only property added to the `esxConfig` is `NumHosts` and `ClusterId` is missed. Compare it to this block of code:

https://github.com/vmware/terraform-provider-vmc/blob/7a0699b1f34909795b53da8af7eb63a652fa4e11/vmc/resource_vmc_cluster.go#L332

When `ClusterId` is not specified, ESX API call will attempt to add/remove hosts to/from Cluster-1. Whereas hosts might have been added/deleted to/from any other cluster - Cluster-2, Cluster-3, etc. Quote from the API documentation:

> Cluster Id is mandatory for non cluster 1 esx remove

https://developer.vmware.com/docs/vmc/latest/vmc/api/orgs/org/sddcs/sddc/esxs/post/

It seems that this issue needs to be fixed together with the other one just submitted: https://github.com/vmware/terraform-provider-vmc/issues/112

If we can track number of hosts in each cluster in the state file, `resourceSddcUpdate` can be updated accordingly to consider multi-cluster SDDC environments.

**Comment by dimitarproynov** [comment]
Fix will be out with next release.
