### ISSUE TITLE
data "vmc_sddc" "sddc" returns error - Expected a value of type 'STRING', but received a value of type 'OPTIONAL' Invalid field 'secret' in structure 'com.vmware.vmc.model.csp_oauth_client'

### ISSUE THREAD

**Issue by vmwbfairclough** [vmware/terraform-provider-vmc#124]
### Describe the bug

Using:

data "vmc_sddc" "sddc" {
  sddc_id = ****
}

returns the following error : 
Error while getting the SDDC with ID ****,  Expected a value of type 'STRING', but received a value of type 'OPTIONAL' Invalid field 'secret' in structure 'com.vmware.vmc.model.csp_oauth_client' Invalid field 'nsx_native_client' in structure 'com.vmware.vmc.model.aws_sddc_resource_config' Invalid field 'resource_config' in structure 'com.vmware.vmc.model.sddc'

### Reproduction steps

```bash
1.Use the data source vmc_sddc to pull sddc details of any SDDC
2.
3.
...
```

### Expected behavior

Returns attributes of the defined SDDC

**Comment by vanditsmehta** [comment]
Duplicate of #123

**Comment by dimitarproynov** [comment]
Closing as duplicate.
