### ISSUE TITLE
Examples still contain reference to r5 (which does not exists in VMC-A service)

### ISSUE THREAD

**Issue by lamw** [vmware/terraform-provider-vmc#128]
### Describe the bug

See https://github.com/vmware/terraform-provider-vmc/blob/master/examples/cluster/variables.tf#L42 and https://github.com/vmware/terraform-provider-vmc/blob/master/examples/cluster/variables.tf#L47 as an example

### Reproduction steps

```bash
N/A
```

### Expected behavior

Should only  mention supported instance types (i3/i3en)

**Comment by dimitarproynov** [comment]
I've removed the references to R5 in the examples, but left the code, so customers with existing R5 environments can continue to manage them via Terraform.
