### ISSUE TITLE
Single Host Deployment

### ISSUE THREAD

**Issue by anthonyspiteri** [vmware/terraform-provider-vmc#129]
### Describe the bug

In the doco is specifies that the minimum number of hosts is 3

https://registry.terraform.io/providers/vmware/vmc/latest/docs/resources/cluster#num_hosts 

### Reproduction steps

```bash
1. Use example config from https://registry.terraform.io/providers/vmware/vmc/latest/
2. init goes through ok
3. apply gives error: 

mc_sddc.sddc_1: Creating...
╷
│ Error:  Failed to create SDDC: [Sddc provisioning requires a minimum of 2 hosts. (code)115 ]

...
```

### Expected behavior

Should be able to set hosts to 1 for Single-Node deployment

**Comment by lamw** [comment]
This is NOT a bug, you did not specify the correct param for 1-Node

By default, the VMC provider will assume you'll want "Production" grade SDDC which means 2 or more hosts.

If you wish to deploy 1-Node, you need to set `sddc_type` to `1NODE` (default value is `DEFAULT` and not required to set) and then specify `sddc_num_hosts` to `1`

**Comment by anthonyspiteri** [comment]
Hey William... yep, that was missed and I knew it was something like that cause of the PowerShell.

That said the doco needs updating: https://registry.terraform.io/providers/vmware/vmc/latest/docs/data-sources/sddc#sddc_type At least to specify the options there.

Cheers
