### ISSUE TITLE
Documentation seem to have typo

### ISSUE THREAD

**Issue by samirshaik** [vmware/terraform-provider-vmc#132]
### Describe the bug

As per documentation vmc_connected_accounts returns a list of connected accounts. Which doesn't seem right as in reality we do not see a list is being returned for a given aws account number. 

https://registry.terraform.io/providers/vmware/vmc/latest/docs/data-sources/connected_accounts

Its a request to review the documentation and update accordingly.

**Comment by dimitarproynov** [comment]
Hi @samirshaik 

According to official documentation the connected_accounts API does indeed return a list:

https://developer.vmware.com/apis/vmc/latest/vmc/api/orgs/org/account-link/get/
