### ISSUE TITLE
Forcing min_hosts to be 3 when in reality 2 is acceptable value

### ISSUE THREAD

**Issue by samirshaik** [vmware/terraform-provider-vmc#136]
### Describe the bug

We are being forced to use minimum value of 3 with following error
```expected min_hosts to be in the range (3 - 16), got 2```

**main.tf**
```
resource "vmc_sddc" "default" {
  ...
  enable_edrs      = var.enable_edrs
  edrs_policy_type = var.edrs_policy_type
  min_hosts        = var.min_hosts
  max_hosts        = var.max_hosts
  ...
}
```
variables.tf
```
variable "min_hosts" {
  type        = string
  description = "The minimum number of hosts that the cluster can scale in to"
  default     = 2

  validation {
    condition     = var.min_hosts >= 2 && var.min_hosts <= 16
    error_message = "Only acceptable values are 2 and 16."
  }
}
```

### Reproduction steps

```bash
1. Create simple main.tf following the documentation
2. Set min_hosts = 2
3. Terraform init
4. Terraform plan
```

### Expected behavior

Expected result:
Plan will work successfully

Actual Result:
ERROR: ```expected min_hosts to be in the range (3 - 16), got 2```

**Comment by samirshaik** [comment]
If this is expected behavior (which may be true, now that I am exploring a bit). It may not hurt to mention the limit in the documentation for min_hosts and max_hosts to avoid any confusion.

**Comment by dimitarproynov** [comment]
Fix is going to be released with next version.
