### ISSUE TITLE
SDDC Group & vTGW resources & data sources

### ISSUE THREAD

**Issue by tlindsay42** [vmware/terraform-provider-vmc#138]
### Is your feature request related to a problem? Please describe.

Customers should be able to deploy & destroy SDDC Groups and vTGW instances with this provider. This would make it easier for customers to deploy, experiment, learn, and manage these resources on their own, for G/SI partners to accelerate deployments on the customer's behalf as well as demo these advanced use cases, and for ISV partners to build & test integrations with their technology.

### Describe the solution you'd like

Deploy & destroy SDDC Groups and vTGW instances with this provider. 

### Describe alternatives you've considered

Manual deployment :thumbsdown:

**Comment by tlindsay42** [comment]
NOTE: This would encompass: https://github.com/vmware/terraform-provider-vmc/issues/64

**Comment by dimitarproynov** [comment]
v1.12.0 is out, bringing support for SDDC Group creation, update members, deletion.

Attaching external TGW support will come in future release, so leaving this bug open.

**Comment by dimitarproynov** [comment]
It seems that 1 SDDC Group = 1 vTGW and there is no API in VMC to create TGW as it is an AWS service. So there won't be any vTGW support in the terraform provider.
