### ISSUE TITLE
Running terraform plan: Error: The terraform-provider-vmc_v1.9.1 plugin crashed!

### ISSUE THREAD

**Issue by bbazan** [vmware/terraform-provider-vmc#139]
### Describe the bug

Attempting terraform plan on an existing environment deployed from terraform, I get "Plugin did not respond" errors

The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-vmc_v1.9.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb232ac]

goroutine 73 [running]:
github.com/vmware/terraform-provider-vmc/vmc.resourceSddcRead(0xc0004f1700, {0xc61900, 0xc000298140})
        github.com/vmware/terraform-provider-vmc/vmc/resource_vmc_sddc.go:487 +0xeec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xcab54b, {0xdd2278, 0xc0001d7340}, 0x24, {0xc61900, 0xc000298140})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003902a0, {0xdd2278, 0xc0001d7340}, 0xc000089e10, {0xc61900, 0xc000298140})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000293ae8, {0xdd2278, 0xc0001d7340}, 0xc0001d73c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000294b00, {0xdd2320, 0xc00035d920}, 0xc0004c8840)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xc7d1e0, 0xc000294b00}, {0xdd2320, 0xc00035d920}, 0xc0004c87e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002ae8c0, {0xde04d8, 0xc000388600}, 0xc0003f8a00, 0xc0003c6ed0, 0x1328430, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0002ae8c0, {0xde04d8, 0xc000388600}, 0xc0003f8a00, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-vmc_v1.9.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Reproduction steps

```bash
1. Build a VMC SDDC running latest version of VMC plugin
2. Run terraform plan after being idle for a few days
3. See above error
```

### Expected behavior

This should output the plan as it was before a few days ago

**Comment by bbazan** [comment]
More info on this. I attempted to import the VMC SDDC into a newly created VM. The import failed as well: 

 Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-vmc_v1.9.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb232ac]

goroutine 84 [running]:
github.com/vmware/terraform-provider-vmc/vmc.resourceSddcRead(0xc0003c0380, {0xc61900, 0xc00034a000})
        github.com/vmware/terraform-provider-vmc/vmc/resource_vmc_sddc.go:487 +0xeec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xcab54b, {0xdd2278, 0xc0005a6680}, 0x24, {0xc61900, 0xc00034a000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004902a0, {0xdd2278, 0xc0005a6680}, 0xc0001241a0, {0xc61900, 0xc00034a000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000391ad0, {0xdd2278, 0xc0005a6680}, 0xc0005a6700)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0003c0a80, {0xdd2320, 0xc00037e420}, 0xc000300420)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xc7d1e0, 0xc0003c0a80}, {0xdd2320, 0xc00037e420}, 0xc0003003c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003ac8c0, {0xde04d8, 0xc000488600}, 0xc0003f6100, 0xc0004c8f00, 0x1328430, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0003ac8c0, {0xde04d8, 0xc000488600}, 0xc0003f6100, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-vmc_v1.9.1 plugin crashed!

**Comment by Girdhar1982** [comment]
Same issues we are facing and error message is also same.. This has started logging after 31 May 

panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                                          
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10ddbf2]                                                                                                                                                          
                                                                                                                                                                                                                                 
goroutine 96 [running]:                                                                                                                                                                                                          
github.com/vmware/terraform-provider-vmc/vmc.resourceSddcRead(0xc000964fc0, 0x130d480, 0xc0005980f0, 0xc000964fc0, 0x0)                                                                                                          
        github.com/vmware/terraform-provider-vmc/vmc/resource_vmc_sddc.go:439 +0xd32                                                                                                                                             
github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0001d6880, 0xc0004443f0, 0x130d480, 0xc0005980f0, 0xc00011a3c0, 0x15ae460, 0xc00011a3c0)                                                       
        github.com/hashicorp/terraform@v0.13.2/helper/schema/resource.go:466 +0x15f                                                                                                                                              
github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000ea70, 0x15ad0e0, 0xc0005f4300, 0xc000b160c0, 0xc00000ea70, 0xc0005f4300, 0xc000807ba0)                                                   
        github.com/hashicorp/terraform@v0.13.2/helper/plugin/grpc_provider.go:543 +0x425                                                                                                                                         
github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler(0x13568a0, 0xc00000ea70, 0x15ad0e0, 0xc0005f4300, 0xc000b16060, 0x0, 0x15ad0e0, 0xc0005f4300, 0xc000a60b00, 0x53c)                              
        github.com/hashicorp/terraform@v0.13.2/internal/tfplugin5/tfplugin5.pb.go:3267 +0x214                                                                                                                                    
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00038e380, 0x15ba420, 0xc000622c00, 0xc000705a00, 0xc000464ff0, 0x1cc7a70, 0x0, 0x0, 0x0)                                                                                    
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x522                                                                                                                                                                     
google.golang.org/grpc.(*Server).handleStream(0xc00038e380, 0x15ba420, 0xc000622c00, 0xc000705a00, 0x0)                                                                                                                          
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05                                                                                                                                                                     
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00030a220, 0xc00038e380, 0x15ba420, 0xc000622c00, 0xc000705a00)                                                                                                         
        google.golang.org/grpc@v1.32.0/server.go:859 +0xa5                                                                                                                                                                       
created by google.golang.org/grpc.(*Server).serveStreams.func1                                                                                                                                                                   
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd                                                                                                                                                                      
                                                                                                                                                                                                                                 
Error: The terraform-provider-vmc_v1.5.1 plugin crashed!

**Comment by dimitarproynov** [comment]
> Same issues we are facing and error message is also same.. This has started logging after 31 May
> 
> panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10ddbf2]
> 
> goroutine 96 [running]: github.com/vmware/terraform-provider-vmc/vmc.resourceSddcRead(0xc000964fc0, 0x130d480, 0xc0005980f0, 0xc000964fc0, 0x0) github.com/vmware/terraform-provider-vmc/vmc/resource_vmc_sddc.go:439 +0xd32 github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0001d6880, 0xc0004443f0, 0x130d480, 0xc0005980f0, 0xc00011a3c0, 0x15ae460, 0xc00011a3c0) github.com/hashicorp/terraform@v0.13.2/helper/schema/resource.go:466 +0x15f github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000ea70, 0x15ad0e0, 0xc0005f4300, 0xc000b160c0, 0xc00000ea70, 0xc0005f4300, 0xc000807ba0) github.com/hashicorp/terraform@v0.13.2/helper/plugin/grpc_provider.go:543 +0x425 github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler(0x13568a0, 0xc00000ea70, 0x15ad0e0, 0xc0005f4300, 0xc000b16060, 0x0, 0x15ad0e0, 0xc0005f4300, 0xc000a60b00, 0x53c) github.com/hashicorp/terraform@v0.13.2/internal/tfplugin5/tfplugin5.pb.go:3267 +0x214 google.golang.org/grpc.(*Server).processUnaryRPC(0xc00038e380, 0x15ba420, 0xc000622c00, 0xc000705a00, 0xc000464ff0, 0x1cc7a70, 0x0, 0x0, 0x0) google.golang.org/grpc@v1.32.0/server.go:1194 +0x522 google.golang.org/grpc.(*Server).handleStream(0xc00038e380, 0x15ba420, 0xc000622c00, 0xc000705a00, 0x0) google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05 google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00030a220, 0xc00038e380, 0x15ba420, 0xc000622c00, 0xc000705a00) google.golang.org/grpc@v1.32.0/server.go:859 +0xa5 created by google.golang.org/grpc.(*Server).serveStreams.func1 google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
> 
> Error: The terraform-provider-vmc_v1.5.1 plugin crashed!

Hi Girdhar,

Try using the latest 1.9.1 version of the provider. If it crashes again, kindly provide steps to reproduce.

Best Regards,
_Proynov

**Comment by Girdhar1982** [comment]
Hi _Proynov... Others experiencing issue with 1.9.1 too, so looks like problem with all the versions.  To reproduce just run the terraform plan.

**Comment by acartag7** [comment]
It is still broken on all versions, maybe something was changed on VMC that is causing this.

```
stack trace from the terraform-provider-vmc_v1.9.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x103586bec]

goroutine 101 [running]:
github.com/vmware/terraform-provider-vmc/vmc.resourceSddcRead(0x14000121900, {0x1037d9000, 0x14000180c80})
	github.com/vmware/terraform-provider-vmc/vmc/resource_vmc_sddc.go:458 +0x96c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1400049a2a0, {0x103841798, 0x140004cc780}, 0x14000121900, {0x1037d9000, 0x14000180c80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x170
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1400049a2a0, {0x103841798, 0x140004cc780}, 0x14000358270, {0x1037d9000, 0x14000180c80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x388
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1400011fad0, {0x103841798, 0x140004cc780}, 0x140004cc800)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x5f4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x14000120b00, {0x103841840, 0x1400042c840}, 0x140001a73e0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x3ac
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1037f4b00, 0x14000120b00}, {0x103841840, 0x1400042c840}, 0x140001a7380, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400013a8c0, {0x10384e578, 0x14000492600}, 0x1400017e600, 0x140004b8f90, 0x103d6a410, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0xc38
google.golang.org/grpc.(*Server).handleStream(0x1400013a8c0, {0x10384e578, 0x14000492600}, 0x1400017e600, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400011baf0, 0x1400013a8c0, {0x10384e578, 0x14000492600}, 0x1400017e600)
	google.golang.org/grpc@v1.32.0/server.go:859 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1f0

Error: The terraform-provider-vmc_v1.9.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by harishkalyanpur** [comment]
@dimitarproynov - Thanks for looking into this issue. Do we have a workaround that can be followed while we are waiting for the fix to be released?

**Comment by dimitarproynov** [comment]
The fix is out with the new release:

https://github.com/vmware/terraform-provider-vmc/releases/tag/v1.9.2

**Comment by dimitarproynov** [comment]
We've tried the binary of the new version in the environment of the bug reporter and the issue seems to be fixed, so I'm closing this bug.

**Comment by harishkalyanpur** [comment]
@dimitarproynov, It failed in our environment though with different error.

Stack trace from the terraform-provider-vmc_v1.9.2 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb798ef]

goroutine 122 [running]:
github.com/vmware/terraform-provider-vmc/vmc.resourceClusterRead(0xc0002d9200, {0xcc9ba0?, 0xc000890000})
	github.com/vmware/terraform-provider-vmc/vmc/resource_vmc_cluster.go:267 +0x80f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xe5f680?, {0xe5f680?, 0xc0003acba0?}, 0xd?, {0xcc9ba0?, 0xc000890000?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.11.0/helper/schema/resource.go:347 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004248c0, {0xe5f680, 0xc0003acba0}, 0xc0000f95f0, {0xcc9ba0, 0xc000890000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.11.0/helper/schema/resource.go:650 +0x47b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00044cbd0, {0xe5f5d8?, 0xc000120d40?}, 0xc000120dc0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.11.0/helper/schema/grpc_provider.go:613 +0x45f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0003fd040, {0xe5f680?, 0xc0003ac180?}, 0xc000a005a0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:746 +0x438
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xce5b40?, 0xc0003fd040}, {0xe5f680, 0xc0003ac180}, 0xc000a00540, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001368c0, {0xe62300, 0xc000483ba0}, 0xc0003a7e60, 0xc00045f050, 0x135d2b0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0001368c0, {0xe62300, 0xc000483ba0}, 0xc0003a7e60, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-vmc_v1.9.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by dimitarproynov** [comment]
@harishkalyanpur I've released a new version, where I think your issue should be fixed:

https://github.com/vmware/terraform-provider-vmc/releases/tag/v1.9.3

**Comment by harishkalyanpur** [comment]
@dimitarproynov - Thanks for the quick fix. Initial tests were successful.
