### ISSUE TITLE
OAuth App support for VMC provider

### ISSUE THREAD

**Issue by Nareshcbit** [vmware/terraform-provider-vmc#164]
### Is your feature request related to a problem? Please describe.

VMWare on AWS supports two types of tokens for accessing API
API Token  : Associated with a user id
OAuth App: Not associated with a user id
Reference: https://vmc.techzone.vmware.com/resource/tech-reference-vmware-cloud-intro-api#
 
However, the terraform documentation(https://registry.terraform.io/providers/vmware/vmc/latest/docs) lists only API Token.
Some organizations don't allow using user api keys as per their security guidelines.

### Describe the solution you'd like

 
VMC provider support OAuth App (server to server).
It would be a great help for organizations that doesn't allow using user api keys as per their security guidelines.

### Describe alternatives you've considered

This is blocking my customer to use terraform.

We are looking at Python to automate SDDC.

**Comment by carsonpadawon** [comment]
I would like to add State Street's request for this.  Their company policy is to use OAuth2 for authentication.  To stick with company directive, they need to authenticate the VMC provider with OAuth2 not API Tokens.

**Comment by vmc-devex** [comment]
@Nareshcbit - could you send me your customer details at mulayp@vmware.com. This will help us prioritize the ask.
@carsonpadawon - acknowledged.

**Comment by dimitarproynov** [comment]
I hope I can release a new version of the provider with the OAuth2.0 App (server-to-server) authentication within a month.

**Comment by dimitarproynov** [comment]
Some security fixes must be merged and the next version of the provider featuring OAuth2.0 App support will be released.

**Comment by dimitarproynov** [comment]
Version 1.13 is out featuring support for OAuth App authentication: 
https://github.com/vmware/terraform-provider-vmc/releases/tag/v1.13
