### ISSUE TITLE
skip_creating_vxlan has no impact

### ISSUE THREAD

**Issue by kremerpatrick** [vmware/terraform-provider-vmc#170]
### Describe the bug

If I set use skip_creating_vxlan to True, the default segment is created anyway.

resource "vmc_sddc" "sddc_a" {
  sddc_name           = var.sddc_a_name
  vpc_cidr            = var.sddc_a_mgmt_cidr
  num_host            = 1
  provider_type       = var.provider_type
  region              = local.sddc_a_region
  delay_account_link  = true
  skip_creating_vxlan = true
  deployment_type     = "SingleAZ"
  sddc_type           = "1NODE"
  host_instance_type  = "I3_METAL"
}

### Reproduction steps

1. Set skip_creating_vxlan to True
2. Deploy an SDDC
3. The default 192.168.1.1/24 sddc-cgw-network-1 segment is created anyway

### Expected behavior

The segment should not be created.

### Additional context

I have tried this in Python against /vmc-aws/operations with a payload that looks like this, and it seems to be ignored as well. This is likely a VMware issue.

    call_data = {
        "type": "DEPLOY",
        "resource_type": "deployment",
        "config": {
            "provider_type": provider_type,
            "name": name,
            "sddc_type": "OneNode",
            "deployment_type": "SingleAZ",
            "type": "DeployVmcAwsSddcConfig",
            "skip_creating_vxlan": "true",
            "host_count": host_count,
            "sddc_size": "medium",
            "location": {
                "name": region,
                "code": region
            },
            "host_type": host_type,
            "network_config": {
                "cidr_block": cidr_block
            }
        }
    }

**Comment by dimitarproynov** [comment]
I've logged an bug to the VMC backend team.

**Comment by dimitarproynov** [comment]
Since this is an issue with the VMC service and no code fixes are required in the Terraform provider I'll be closing the issue, but will be monitoring the bug, logged in the VMC backend's backlog.
