### ISSUE TITLE
Remove skip_creating_vxlan parameter as it has no affect

### ISSUE THREAD

**Issue by uprightvinyl** [vmware/terraform-provider-vmc#174]
### Is your feature request related to a problem? Please describe.

As per #170, the skip_creating_vxlan parameter no longer works, despite being available for configuration within the provider. 

### Describe the solution you'd like

skip_creating_vxlan should be removed as a parameter from the provider until changing it has any affect. In the current state it is confusing to use as changing this parameter has no affect. 

### Describe alternatives you've considered

Documentation could be updated to note that changing this parameter has no affect

**Comment by dimitarproynov** [comment]
VMC backend teams have acknowledged the issue (took a while), have reproduced it and are working on a fix. Thus there will be no need to remove the attribute from the configuration/documentation.
