### ISSUE TITLE
Error while reading ORG information

### ISSUE THREAD

**Issue by gchek** [vmware/terraform-provider-vmc#18]
While doing `terraform apply` I am getting errors:
`module.SDDC.vmc_sddc.Terraform_SDDC1: Refreshing state... [id=96ca6d5a-0ca3-4948-ab35-103706bbb089]
module.VPCs.aws_default_security_group.default: Refreshing state... [id=sg-0ea193c3f8a3d96ca]
module.EC2s.aws_network_interface.TKG-Eth0: Refreshing state... [id=eni-0979a65a7fdd9c3b6]
module.EC2s.aws_instance.TKG: Refreshing state... [id=i-0f23b48ac1ca9066d]
module.VPCs.aws_route_table_association.vpc1_10: Refreshing state... [id=rtbassoc-0c9a4df41c1feb107]
module.VPCs.aws_vpc_endpoint.s3: Refreshing state... [id=vpce-0f55075211abedacc]`

`Error: Error while reading org information for 7421a286-f7bf-4f34-8567-779b83d75fb5:  Expected a value of type 'StructValue', but received a value of type '*data.ListValue'`

  `on ../SDDC/SDDC.tf line 10, in data "vmc_org" "my_org":
  10: data "vmc_org" "my_org" {
`
Not always - this is from time to time.
Re launching `terraform apply` goes through the socond or third time

**Comment by saloneerege** [comment]
Thanks @gchek for reporting this issue. We will look into it and give you an update.

**Comment by xfirestyle2k** [comment]
I am running in this error often times as well, any updates here?

**Comment by xfirestyle2k** [comment]
Hi,
gchek helped me with this error and it is resolved! THANKS A TON!
Solution is to remove:

# Empty data source defined in order to store the org display name and name in terraform state
data "vmc_org" "my_org" {
}

it is not longer needed. Can you please change this in the Example/SDDC folder?
Thanks!
