### ISSUE TITLE
Terraform apply failed with error Invalid Microsoft Licensing Config

### ISSUE THREAD

**Issue by Nareshcbit** [vmware/terraform-provider-vmc#187]
### Describe the bug

Error: Failed to create SDDC: [Invalid Microsoft Licensing config provided for provisioning request MicrosoftLicensingConfig(windowsLicensing=DISABLED, mssqlLicensing=DISABLED, academicLicense=null). Please use Microsoft licensing publish APIs for activation. (code)115 ]

### Reproduction steps

provider "vmc" {
  refresh_token = var.api_token
  org_id = var.org_id
}

data "vmc_connected_accounts" "my_accounts" {
  account_number = var.aws_account_number
}

data "vmc_customer_subnets" "my_subnets" {
  connected_account_id = data.vmc_connected_accounts.my_accounts.id
  region               = var.sddc_region
}

resource "vmc_sddc" "sddc_1" {
  sddc_name           = var.sddc_name
  vpc_cidr            = var.vpc_cidr
  num_host            = 1
  provider_type       = "AWS"
  region              = data.vmc_customer_subnets.my_subnets.region
  vxlan_subnet        = var.vxlan_subnet
  delay_account_link  = false
  skip_creating_vxlan = false
  sso_domain          = "vmc.local"
  deployment_type = "SingleAZ"
  sddc_type ="1NODE"
  account_link_sddc_config {
    customer_subnet_ids  = [data.vmc_customer_subnets.my_subnets.ids[0]]
    connected_account_id = data.vmc_connected_accounts.my_accounts.id
  }
  microsoft_licensing_config {
   mssql_licensing = "ENABLED"
   windows_licensing = "DISABLED"
  }
}

1. Terraform plan
2. Terraform apply

### Expected behavior

SDDC is deployed successfully

### Additional context

When the below microsoft licensing config is not provided in SDDC resource, the deployment works.

resource "vmc_sddc" "sddc_1" {
  sddc_name           = var.sddc_name
  vpc_cidr            = var.vpc_cidr
  num_host            = 1
  provider_type       = "AWS"
  region              = data.vmc_customer_subnets.my_subnets.region
  vxlan_subnet        = var.vxlan_subnet
  delay_account_link  = false
  skip_creating_vxlan = false
  sso_domain          = "vmc.local"
  deployment_type = "SingleAZ"
  sddc_type ="1NODE"
  account_link_sddc_config {
    customer_subnet_ids  = [data.vmc_customer_subnets.my_subnets.ids[0]]
    connected_account_id = data.vmc_connected_accounts.my_accounts.id
  }

}

**Comment by Anglosk** [comment]
Came here to log this too.  Hope this assists:-
a) Provider source code doesn't account for the academic license.
b) Vmware API doc states 'academic license' should be a Boolean as opposed to the original two values being String values:
https://developer.vmware.com/apis/vmc/latest/vmc/api/orgs/org/sddcs/sddc/clusters/cluster/msft-licensing/publish/post/
