### ISSUE TITLE
Modifying SDDC name in GUI doesn't reflect on Terraform

### ISSUE THREAD

**Issue by kolkes** [vmware/terraform-provider-vmc#28]
After changing the name of my Terraform deployed SDDC from the GUI and later running `Terraform Refresh` to update the configuration, there is no update happening and the .tfstate file continues to show original SDDC name.

**Comment by saloneerege** [comment]
Thank for reporting this issue @kolkes. As per our discussion, I will push a fix for this issue in the next release of the provider.
