### ISSUE TITLE
Resource should be re-created if manually destroyed

### ISSUE THREAD

**Issue by gchek** [vmware/terraform-provider-vmc#3]
I was hitting an issue today when I accidently deleted a resource that was created with VMC Terraform.
I had a public IP created with the provider and so described in my terraform.tfstate.
 
When I did a second apply, I got the following error:
`Error: Error getting public IP with ID 1e5dafc7-2e34-4822-a645-0ce1a8a0b09f : com.vmware.vapi.std.errors.not_found`
 
That’s normal since the resource has been manually deleted.
At this stage, I am totally stuck until I go and manually remove that section in the .tfstate file and this is NOT something we should do.
 
My view on that is we should **re-create** the resource to honour the end-state of the code.
 
By the way, if I do something similar with AWS provider like removing a subnet in a VPC, it will re-create another one.

**Comment by shylasrinivas** [comment]
@gchek Thanks for reporting the issue. We will look into it.
