### ISSUE TITLE
If main cluster is stretched, all new clusters in that SDDC must be stretched.

### ISSUE THREAD

**Issue by gchek** [vmware/terraform-provider-vmc#44]
No mix between stretched and non stretched in one SDDC.
Must be same type. can be different host type

**Comment by saloneerege** [comment]
Thanks @gchek for reporting the issue. We will look into it.

**Comment by saloneerege** [comment]
After conformation from VMware Cloud on AWS team, this is not a bug. The secondary clusters for an SDDC has the same deployment type as the SDDC itself. So if the SDDC deployment type is "MultiAZ" then the secondary clusters will also be stretched.
