### ISSUE TITLE
If multiple values are provided in account_link_sddc_config.customer_subnet_ids the SDDC deployment fails and SDDC cannot be removed.

### ISSUE THREAD

**Issue by AdrianBegg** [vmware/terraform-provider-vmc#50]
If the attribute customer_subnet_ids.connected_account_id is provided multiple objects (example an array of 3 subnet Id's) the terraform apply attempts to deploy the SDDC however the VMC Console reports "com.vmware.skyscraper.common.SkyscraperException: The provided account linking data contains more than one subnet for XXXXX. Only one is supported.:skyscraper.sddc.provision.config.too.many.subnets".

The resulting object can also not be removed from VMC by a customer. Would be good if there was input checking in place to avoid this from occurring.

**Comment by saloneerege** [comment]
@AdrianBegg thank you for reporting this issue.  We will look into it.

**Comment by saloneerege** [comment]
@AdrianBegg This fix has been merged to the master branch.

**Comment by saloneerege** [comment]
Input validation corrected for customer_subnet_ids . Closing this issue.
