### ISSUE TITLE
resource_vmc_sddc: missing attribute "size" to control SDDC size medium/large

### ISSUE THREAD

**Issue by AdrianBegg** [vmware/terraform-provider-vmc#51]
Hi, there is currently small coverage gap on the resource_vmc_sddc and no ability to define the SDDC attribute "size"/"sddcSize"  We require the ability to deploy sddcSize "large" using the SDDC (The size of the vCenter and NSX appliances). The attribute is currently not exposed and as such only the default "medium" can be deployed with the provider.

**Comment by saloneerege** [comment]
@AdrianBegg Thank you for reporting this issue. We will be working on adding support for the attribute "size" in the next quarter.
