### ISSUE TITLE
SDDC API documentation is incomplete

### ISSUE THREAD

**Issue by vbuild2bau** [vmware/terraform-provider-vmc#60]
Referencing : https://developer.vmware.com/docs/vmc/latest/vmc/api/orgs/org/sddcs/post/
 
The field “sddc_type” does not document what the valid values are.  This leaves us guessing as to what to use, and in fact makes it near impossible to divine the correct API call to enable single host SDDC.
 
In comparison, the field “deployment_type” is properly documented with possible values.”

**Comment by shylasrinivas** [comment]
@vbuild2bau thank you, we appreciate your feedback on the documentation. We are working with the VMC team to have more details added.

**Comment by matt-dreyer** [comment]
Sorry about this.  This field may be populated as follows:

#normal SDDCs with 3-max hosts
sddc_type:  null

#Single Host SDDC 
sddc_type: "1NODE"

**Comment by vbuild2bau** [comment]
No probs.  Thanks for your efforts and prompt response.
