### ISSUE TITLE
Feature Request : Remove SDDC Group

### ISSUE THREAD

**Issue by vbuild2bau** [vmware/terraform-provider-vmc#64]
Feature Request : Remove SDDC Group from VMC TF Provider.

At the moment VMC TF Provider can tear down SDDC with no checks if VTGW (SDDC Groups) is configured.  If SDDC is torn down without first removing SDDC Groups this can cause an issues that require backend support assistance.

Can we please add support within VMC TF Provider to tear down SDDC Groups.
And if possible a pre-check to make sure that SDDC Groups don't exist before tearing down the SDDC.

**Comment by saloneerege** [comment]
@vbuild2bau Thank you for submitting this feature request. We will look into it.

**Comment by dimitarproynov** [comment]
v.1.12.0 is out bringing support for SDDC groups

https://github.com/vmware/terraform-provider-vmc/releases/tag/v1.12.0
