### ISSUE TITLE
Feature Request : Configure SDDC Intranet Uplink MTU setting via terraform

### ISSUE THREAD

**Issue by AdrianBegg** [vmware/terraform-provider-vmc#68]
Could support please be added to the provider to set the Intranet Uplink MTU for the SDDC (SDDC > Networking & Security > Global Configuration > Intranet Uplink MTU). 

With the MTU set to the default 1500 the throughput becomes constrained between the AWS Connected VPC and services hosted on the on-premises site (via DX); we have seen significant throughput increases using Jumbo Frames (e.g. backup streams to EC2 instances) however at the moment we have to manually set this value. It would be useful for us to be able to manage this value using the terraform provider.

**Comment by saloneerege** [comment]
Thank you for reporting this issue. We will look into it.

**Comment by AdrianBegg** [comment]
After testing under v1.5.0 terraform it still does not appear to be possible to set/adjust this value in the vmc_sddc resource via terraform. 

When adding "intranet_uplink_mtu = 1500" in the vmc_sddc resource under v1.5.0 terraform throws:
"Error: Unsupported argument
  on main.tf line 95, in resource "vmc_sddc" "SDDC":
  95:   intranet_uplink_mtu = 1500 # Uplink MTU of direct connect, sddc-grouping and outposts traffic in edge tier-0 router port
An argument named "intranet_uplink_mtu" is not expected here."

The attribute is present in the state file however there is no mechanism to adjust it - from the comments about the attribute that has been added I can see that it can not be set at Create. Is there a way using the provider to adjust the value ?

Could the not being able to be set during Create maybe be solved by abstracting it as an independent resource object (similar to the Public IP object) and the dependency can be built after the vmc_sddc object ?

**Comment by saloneerege** [comment]
@AdrianBegg , thanks for using v1.5 of the provider and reporting your findings. The intranet_uplink_mtu attribute is an update attribute for SDDC resource. During SDDC creation the default value of 1500 is stored in the tf state file. After SDDC is created you can update the field and that calls the SDDC resource's Update method. As far as supporting it as a separate resource in the provider, intranet_uplink_mtu might not fit the definition of a resource where resource is an infrastructure object.

**Comment by AdrianBegg** [comment]
@saloneerege thank you for the additional information, it's a really good provider with good functional coverage and we are getting a lot of value out of it for management of our VMC product offerings. 

I have done some further testing today  with the "intranet_mtu_uplink" attribute in the vmc_sddc resource block and everything is working as expected so I assume that there was some "user error" running against the incorrect provider version last week 🤦total misunderstanding on my part so sorry for any confusion (fine as it is defined) I just have to adjust my pipeline to do a second `terraform apply` with resource targeting against the vmc_sddc objects after the create to kick off the update which is perfectly fine.

Top work, thank you for all the efforts.

**Comment by saloneerege** [comment]
@AdrianBegg thanks for testing the provider with the enhancement and thank you for using the provider.
