### ISSUE TITLE
Broken "vmc_sddc" resource example usage due to change in "vmc_connected_accounts" data source

### ISSUE THREAD

**Issue by nibrahv** [vmware/terraform-provider-vmc#70]
Usage example in Terraform registry for "vmc_sddc" resource is incorrect due to change to "vmc_connected_accounts" data source.  "vmc_connected_accounts" now returns "id" attribute, rather than "ids[n]" attribute.

Reference:
https://registry.terraform.io/providers/vmware/vmc/latest/docs/resources/sddc

_Not working:_
data "vmc_customer_subnets" "my_subnets" {
  **connected_account_id = data.vmc_connected_accounts.my_accounts.ids[0]**
  region               = var.sddc_region

_Potential fix:_
data "vmc_customer_subnets" "my_subnets" {
  **connected_account_id = data.vmc_connected_accounts.my_accounts.id**
  region               = var.sddc_region

**Comment by saloneerege** [comment]
@nibrahv Thanks for reporting this issue. That is an error in documentation for the resource. We will definitely get that fixed soon.
