### ISSUE TITLE
Terraform registry doc: Customer subnets

### ISSUE THREAD

**Issue by gchek** [vmware/terraform-provider-vmc#74]
https://registry.terraform.io/providers/vmware/vmc/latest/docs/data-sources/customer_subnets
why `num_hosts` and `instance_type` are there?

**Comment by saloneerege** [comment]
Thanks for reporting this. After looking into the definition for the GET API to confirm why these fields were added in the data resource, I found that fields like num_hosts, instance_type, sddc_id, sddc_type are optional parameters. These have been defined by the API and hence I have  added these to the data source customer_subnets.
