### ISSUE TITLE
TF 0.13 - Error deployment type SingleAZ requires 1 subnet ID 

### ISSUE THREAD

**Issue by gchek** [vmware/terraform-provider-vmc#75]
With NO CODE CHANGES from 0.12 version, 0.13  complains  about customer subnet needed where it's clearly coded:
```
data "vmc_connected_accounts" "my_accounts" {
  account_number = var.AWS_account
}
/*==========================
Create SDDC 1 node
==========================*/
resource "vmc_sddc" "Terraform_SDDC1" {
    sddc_name           = "Terraform_SDDC"
    vpc_cidr            = var.SDDC_Mngt
    num_host            = 1
    provider_type       = "AWS"
    region              = replace(upper(var.region), "-", "_")
    vxlan_subnet        = var.SDDC_default
    delay_account_link  = false
    skip_creating_vxlan = false
    host_instance_type  = "I3_METAL"
    sso_domain          = "vmc.local"
    deployment_type     = "SingleAZ"
    sddc_type           = "1NODE"
    account_link_sddc_config {
        customer_subnet_ids  = [var.Att_vpc_subnet_id]
        connected_account_id = data.vmc_connected_accounts.my_accounts.id
    }
    timeouts {
        create = "300m"
        update = "300m"
        delete = "180m"
    }
}
```

**Comment by uprightvinyl** [comment]
I'm also seeing this same issue, error is:

`Error: deployment type SingleAZ requires 1 subnet ID `

I get a similar error for MultiAZ:

`Error: deployment type MultiAZ requires 2 subnet IDs, one in each availability zone `

```
resource "vmc_sddc" "sddc" {
  sddc_name           = var.sddc_name
  vpc_cidr            = var.sddc_mgmt_cidr
  num_host            = 6
  provider_type       = "AWS"
  region              = var.sddc_region
  delay_account_link  = false
  skip_creating_vxlan = false
  sso_domain          = "vmc.local"
  deployment_type     = "MultiAZ"

  account_link_sddc_config {
    customer_subnet_ids  = [var.aws_subnets[0].id,var.aws_subnets[1].id]
    connected_account_id = data.vmc_connected_accounts.vmc_connected_account.id
  }

}
```

**Comment by saloneerege** [comment]
@uprightvinyl thanks for reporting this issue. Can you share your config (.tf)  file ?

**Comment by uprightvinyl** [comment]
Upon further testing, I am able to replicate this error in both Terraform 0.12 and 0.13. The issue appears to be if the subnet used for `customer_subnet_ids` is being created at the same time as the SDDC. If I rename sddc.tf to sddc.tf.ignore, create the VPC and subnets, then re-run apply with sddc.tf renamed, it runs successfully. Trying to run in the same phase generates the error from my previous comment.

### aws_vpc.tf
```
provider "aws" {
  region = var.sddc_cloud_region
}

data "aws_availability_zones" "available" {}

resource "aws_vpc" "connected_vpc" {
  cidr_block = var.connected_vpc_cidr

  tags = {
    Name = "connected_vpc"
  }

}

resource "aws_subnet" "connected_vpc_subnet" {
  count             = 2
  vpc_id            = aws_vpc.connected_vpc.id
  cidr_block        = cidrsubnet(aws_vpc.connected_vpc.cidr_block, 8, count.index)
  availability_zone = data.aws_availability_zones.available.names[count.index]

  tags = {
    Name = "connected_vpc_subnet${count.index}"
  }
}
```
### sddc.tf
```
provider "vmc" {
  refresh_token = var.vmc_refresh_token
  org_id        = var.vmc_org_id
}

data "vmc_connected_accounts" "vmc_connected_account" {
  account_number = var.aws_account_number
}

resource "vmc_sddc" "sddc_cloud" {
  sddc_name           = "SDDC Cloud"
  vpc_cidr            = var.sddc_cloud_vpc_cidr
  num_host            = 1
  provider_type       = "AWS"
  region              = var.sddc_cloud_region
  delay_account_link  = true
  skip_creating_vxlan = false
  sso_domain          = "vmc.local"
  deployment_type     = "SingleAZ"

  account_link_sddc_config {
    customer_subnet_ids  = [aws_subnet.connected_vpc_subnet[0].id]
    connected_account_id = data.vmc_connected_accounts.vmc_connected_account.id
  }

}

output "nsxt_url" {
  value = vmc_sddc.sddc_cloud.nsxt_reverse_proxy_url
}
```
### variables.tf
```
variable "vmc_refresh_token" {}
variable "vmc_org_id" {}
variable "sddc_cloud_region" {}
variable "connected_vpc_cidr" { default = "172.16.0.0/16" }
variable "sddc_cloud_vpc_cidr" { default = "10.2.0.0/16" }
variable "aws_account_number" {}
```

I have tried adding an explicit dependency between the SDDC creation and subnet creation using `depends_on = [aws_subnet.connected_vpc_subnet]`,  but the error still persists.

**Comment by gchek** [comment]
I never had that with 0.12 and ALWAYS created the VPC/subnet and SDDC in the same apply. 
With 0.13 the same code complains that the subnet is not defined 

Gilles 

> On 21 Nov 2020, at 08:43, Chris Porter <notifications@github.com> wrote:
> 

﻿
Upon further testing, I am able to replicate this error in both Terraform 0.12 and 0.13. The issue appears to be if the subnet used for customer_subnet_ids is being created at the same time as the SDDC. If I rename sddc.tf to sddc.tf.ignore, create the VPC and subnets, then re-run apply with sddc.tf renamed, it runs successfully. Trying to run in the same phase generates the error from my previous comment.

aws_vpc.tf

provider "aws" {
  region = var.sddc_cloud_region
}

data "aws_availability_zones" "available" {}

resource "aws_vpc" "connected_vpc" {
  cidr_block = var.connected_vpc_cidr

  tags = {
    Name = "connected_vpc"
  }

}

resource "aws_subnet" "connected_vpc_subnet" {
  count             = 2
  vpc_id            = aws_vpc.connected_vpc.id
  cidr_block        = cidrsubnet(aws_vpc.connected_vpc.cidr_block, 8, count.index)
  availability_zone = data.aws_availability_zones.available.names[count.index]

  tags = {
    Name = "connected_vpc_subnet${count.index}"
  }
}
sddc.tf

provider "vmc" {
  refresh_token = var.vmc_refresh_token
  org_id        = var.vmc_org_id
}

data "vmc_connected_accounts" "vmc_connected_account" {
  account_number = var.aws_account_number
}

resource "vmc_sddc" "sddc_cloud" {
  sddc_name           = "SDDC Cloud"
  vpc_cidr            = var.sddc_cloud_vpc_cidr
  num_host            = 1
  provider_type       = "AWS"
  region              = var.sddc_cloud_region
  delay_account_link  = true
  skip_creating_vxlan = false
  sso_domain          = "vmc.local"
  deployment_type     = "SingleAZ"

  account_link_sddc_config {
    customer_subnet_ids  = [aws_subnet.connected_vpc_subnet[0].id]
    connected_account_id = data.vmc_connected_accounts.vmc_connected_account.id
  }

}

output "nsxt_url" {
  value = vmc_sddc.sddc_cloud.nsxt_reverse_proxy_url
}
variables.tf

variable "vmc_refresh_token" {}
variable "vmc_org_id" {}
variable "sddc_cloud_region" {}
variable "connected_vpc_cidr" { default = "172.16.0.0/16" }
variable "sddc_cloud_vpc_cidr" { default = "10.2.0.0/16" }
variable "aws_account_number" {}
I have tried adding an explicit dependency between the SDDC creation and subnet creation using depends_on = [aws_subnet.connected_vpc_subnet], but the error still persists.

**Comment by uprightvinyl** [comment]
With further testing, this appears to be a bug in terraform-providers/vmc v1.4.0. If I set the version to 1.3.0 for the vmc provider, I do not get the error, using Terraform v0.12 or 0.13.

I get the error with the following version info:

```
Terraform v0.12.29
+ provider.aws v3.16.0
+ provider.vmc v1.4.0
```

or using v0.13:

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.16.0
+ provider registry.terraform.io/terraform-providers/vmc v1.4.0
```

However the error does not occur with the previous vmc version:

```
Terraform v0.12.29
+ provider.aws v3.16.0
+ provider.vmc v1.3.0
```
and 
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.16.0
+ provider registry.terraform.io/terraform-providers/vmc v1.3.0
```

@gchek, could this possible be that after upgrading to Terraform 0.13, the reinitialisation pulled down a later version of the VMC provider than you had been using previously? If you add `version = "~> 1.3.0"` to the vmc provider configuration within the `required_providers` block, does the issue go away?

**Comment by gchek** [comment]
Yes Chris. 
It’s possible because when I upgraded to 0.13 I re-init by removing the .terraform directory and did terraform init again so latest version is pulled in. 

Gilles 

> On 21 Nov 2020, at 18:53, Chris Porter <notifications@github.com> wrote:
> 

﻿
With further testing, this appears to be a bug in terraform-providers/vmc v1.4.0. If I set the version to 1.3.0 for the vmc provider, I do not get the error, using Terraform v0.12 or 0.13.

I get the error with the following version info:

Terraform v0.12.29
+ provider.aws v3.16.0
+ provider.vmc v1.4.0
or using v0.13:

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.16.0
+ provider registry.terraform.io/terraform-providers/vmc v1.4.0
However the error does not occur with the previous vmc version:

Terraform v0.12.29
+ provider.aws v3.16.0
+ provider.vmc v1.3.0
and

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.16.0
+ provider registry.terraform.io/terraform-providers/vmc v1.3.0
@gchek, could this possible be that after upgrading to Terraform 0.13, the reinitialisation pulled down a later version of the VMC provider than you had been using previously? If you add version = "~> 1.3.0" to the vmc provider configuration within the required_providers block, does the issue go away?

**Comment by saloneerege** [comment]
Thanks for providing detailed steps for reproducing the issue. We will look into it. @uprightvinyl

**Comment by shylasrinivas** [comment]
@gchek I haven't been able to reproduce this issue with vmc tf provider v1.4.0 and an already existing subnet. 
Can you share the output of terraform plan? I believe a check was added in v1.4.0 for subnets to be present during SDDC create. This could be the reason for the error (since subnet is being created at the same time as sddc).

I can setup a call with you to discuss further.

**Comment by uprightvinyl** [comment]
@shylasrinivas Thanks for the update. I have retested with v1.5.0 and this issue is still occurring. To recreate this issue, you will need to be creating the AWS subnet in the same ``terraform apply`` as the SDDC. This worked in v1.3, but it would appear the check added in 1.4, to see if the subnet is present, is breaking creation of the subnet at the same time as the SDDC. The check seems to be ignoring implicit resource dependencies, between the creation of the SDDC and the creation of the linked AWS subnet. Can the check be removed, or skipped if the subnet is being created along with the SDDC? In its current state, this is breaking any automation workflow that creates the SDDC AWS resources (VPC/subnet) and the SDDC at the same time. As such, I'm currently having to pin the vmc provider to v1.3 in my code.

**Comment by gchek** [comment]
you should not expect the subnet to be created.
the `customer_subnet_ids` can be a variable
in my code  - it is. and Terraform will create precedence of creating the subnet before creating the SDDC during apply

**Comment by shylasrinivas** [comment]
@uprightvinyl Thank you for retesting. Yes, a check was added in 1.4.0 which is causing the issue 1.3.0 onwards. This check was added to validate number of subnets for SingleAZ vs MultiAZ and to provide a meaningful message back to the user. I am looking at how to workaround this in the code and should have a fix ready soon.
