### ISSUE TITLE
sddc_type = “DEFAULT” seen as new addition on each apply 

### ISSUE THREAD

**Issue by TP-87** [vmware/terraform-provider-vmc#78]
On version 1.3 I had been leaving this blank sddc_type = “” This then used the default of DEFAULT the reason I did this is that if I specified DEFAULT each apply was wanting to replace the whole sddc where leaving blank worked fine with no issues.

On version 1.4 when our code used  sddc_type = “” this caused an error Error: expected sddc_type to be one of [1NODE DEFAULT], So I have replaced the variable with sddc_type = “DEFAULT” however post build this is seems to be a value that’s to be added on every apply it is being marked down as something that needs to be added so it appears there is a change to the sddc when there isn’t + sddc_type              = "DEFAULT"/ Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by saloneerege** [comment]
Thanks for reporting this issue. It has already been resolved and merged into the master branch
