### ISSUE TITLE
min_hosts key:value shows as a change on each apply when using Stretched SDDC

### ISSUE THREAD

**Issue by TP-87** [vmware/terraform-provider-vmc#79]
When run plans/applies against a stretched sddc post build I am seeing  ~ min_hosts   = 6 -> 3  causing the output that the sddc is to be changed rather than everything is up to date.

**Comment by saloneerege** [comment]
Thank you for reporting this issue. We will look into it

**Comment by saloneerege** [comment]
The default for the field min_host was 3. As a result a terraform apply for a stretched SDDC would try to change the value to the default 3. We have now removed default on min_host defined in schema. Instead the resource's Read operation stores the default value for the field from the backend in the terraform state file. Closing this issue.
