### ISSUE TITLE
key:value vxlan_subnet is being populated when skip_creating_vxlan = true 

### ISSUE THREAD

**Issue by TP-87** [vmware/terraform-provider-vmc#80]
When I have no value for vxlan_subnet due to skipping the creation, I can see that it appears that a vxlan subnet has been created anyway with vxlan_subnet  = "192.168.1.0/24"  

I can see that the segment has not been created so seems to just be a value populated on the backend that is now being pulled in the code the issue is that because we don’t have that value in our code the resetting this value to “null” is forcing a replacement of the sddc  - vxlan_subnet = "192.168.1.0/24" -> null # forces replacement 

This same config worked without issues when using version 1.3

**Comment by saloneerege** [comment]
Thanks for reporting this issue. I will look into it.

**Comment by shylasrinivas** [comment]
@TP-87 fix for this issue is now available in the latest release [v1.5.0](https://github.com/vmware/terraform-provider-vmc/releases/tag/v1.5.0)
