### ISSUE TITLE
Provider does not detect failed SDDC create, waits forever

### ISSUE THREAD

**Issue by jontyq** [vmware/terraform-provider-vmc#82]
If an SDDC fails to create, the `vmc_sddc` resource will wait forever for the creation to succeed, instead of reporting the error.

Screenshot of SDDC in failed state:
![image](https://user-images.githubusercontent.com/2671668/100042465-9b777480-2e5f-11eb-892c-c1ef95296711.png)

Our Terraform `create` timeout is set to 300 minutes.  Our pipeline thus finished at the 5 hour mark below, instead of finishing as soon as the SDDC entered FAILED state:

Log output:
```
...
module.sddc-1.vmc_sddc.this: Still creating... [4h59m50s elapsed]
module.sddc-1.vmc_sddc.this: Still creating... [5h0m0s elapsed]
                                                                                                                                                  
Error: expected instance to be created but was in state FAILED 
                                                                                                                                                  
  on module/SDDC/main.tf line 1, in resource "vmc_sddc" "this":                      
   1: resource "vmc_sddc" "this" {                                                             

```

**Comment by saloneerege** [comment]
Thanks for reporting this issue. We will look into it.

**Comment by saloneerege** [comment]
Added an explicit check for returning an error when the SDDC creation returns a FAILED status. Closing this issue.
