### ISSUE TITLE
Feature Request: New Resource - vmc.hcx

### ISSUE THREAD

**Issue by uprightvinyl** [vmware/terraform-provider-vmc#84]
Similar to the vmc_site_recovery resource, it would be useful to be able to enable the HCX add on via Terraform.

**Comment by saloneerege** [comment]
@uprightvinyl Thanks for reporting this feature request. We will look into it.

**Comment by dimitarproynov** [comment]
The HCX add on is active by default on new SDDC deployments, so this bug has lost its relevance. Closing.

**Comment by uprightvinyl** [comment]
Please could this issue be reopened. The feature request is to trigger the deployment of HCX within an SDDC, which does not happen by default.

**Comment by dimitarproynov** [comment]
Hi,

It seems that the activation of the HCX is actually not a VMC API. However, there is a HCX Terraform provider that covers the activation of HCX on an SDDC, please refer to:

https://github.com/adeleporte/terraform-provider-hcx/blob/main/docs/guides/vmc.md

https://registry.terraform.io/providers/adeleporte/hcx/0.4.2

Regards,
_Proynov
