### ISSUE TITLE
Some descriptions in variables.tf need update

### ISSUE THREAD

**Issue by gchek** [vmware/terraform-provider-vmc#9]
`Create SDDC` was probably one of the first API created for VMC.
Some of the field descriptions are miss-leading, sometimes not updated, sometimes out-dated.

We need to fix 2 variables description in particular:

```
variable "vpc_cidr" {
```
  description = "AWS VPC IP range. Only prefix of 16 or 20 is currently supported."

Change to : “ the SDDC  management network CIDR. Only prefix of 16, 20 and 23 are supported
- Specify a private subnet range (RFC 1918) to be used for vCenter Server, NSX Manager, and ESXi hosts.
- Choose a range that will not conflict with other networks you will connect to this SDDC.
- Minimum CIDR sizes: /23 for up to 27 hosts, /20 for up to 251 hosts, /16 for up to 4091 hosts.
- Reserved CIDRs: 10.0.0.0/15, 172.31.0.0/16. ”
```
  default     = "10.2.0.0/16"
}
```
and Also . . .
```
variable "vxlan_subnet" {
```
 description = "VXLAN IP subnet in CIDR for compute gateway."
Change to “ A logical segment that will be created with the SDDC under the compute gateway.”
```  
default     = "192.168.1.0/24"
}
```
(there is No VXLAN in VMC anymore - this was from NSX-V early deployments)

**Comment by saloneerege** [comment]
Thanks @gchek for raising this issue and providing your feedback. We will update the document.
