### ISSUE TITLE
vmc_cluster resource tries to create new clusters simultaneously 

### ISSUE THREAD

**Issue by jsowerby** [vmware/terraform-provider-vmc#93]
when creating multiple addition clusters within an SDDC the vmc provider attempt to create all clusters simultaneously which causes an error

**Behaviour**

The plan shows the creation of 2 additional clusters

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  module.singleAZ.vmc_cluster.this["Cluster_2"] will be created
  + resource "vmc_cluster" "this" {
      + cluster_info     = (known after apply)
      + edrs_policy_type = "storage-scaleup"
      + enable_edrs      = true
      + id               = (known after apply)
      + max_hosts        = 16
      + min_hosts        = 3
      + num_hosts        = 3
      + sddc_id          = "redacted"
    }

   module.singleAZ.vmc_cluster.this["Cluster_3"] will be created
  + resource "vmc_cluster" "this" {
      + cluster_info     = (known after apply)
      + edrs_policy_type = "storage-scaleup"
      + enable_edrs      = true
      + id               = (known after apply)
      + max_hosts        = 16
      + min_hosts        = 3
      + num_hosts        = 3
      + sddc_id          = "redacted"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```
when the apply is run the first cluster is created, the second fails

```
module.singleAZ.vmc_cluster.this["Cluster_2"]: Creating...
module.singleAZ.vmc_cluster.this["Cluster_3"]: Creating...
module.singleAZ.vmc_cluster.this["Cluster_2"]: Still creating... [10s elapsed]
module.singleAZ.vmc_cluster.this["Cluster_2"]: Still creating... [20s elapsed]
module.singleAZ.vmc_cluster.this["Cluster_2"]: Still creating... [30s elapsed]
...
...
...
module.singleAZ.vmc_cluster.this["Cluster_2"]: Creation complete after 27m31s [id=842858a8-96c8-4555-aaa5-147bfd5b4e7e]

Error: task failed to create cluster`
```

**Expected Behaviour**

Both clusters are created in a single apply step

**Comment by jontyq** [comment]
Yes, we have experienced this.  API only allows sequential creation, please make the provider do the creation sequentially too.

**Comment by gchek** [comment]
use     `depends_on = []` and set your creation sequence

**Comment by jontyq** [comment]
You could, however that would take much away from our sddc module, where the cluster list is a map supplied to the module.

The module employs a `for_each` on the cluster resource.

We are now left in the situation of having to write big warnings about code reviews to never add more than one cluster at a time ... and in a DR situation, our code can not simply be 're-applied' since multiple clusters will probably be in effect by then.

Hoping for a provider fix before this situation arises!

**Comment by dimitarproynov** [comment]
Sadly there is no Terraform SDK feature to have a parallelisim control over the provider. I'll have to use a generic Go Mutex or something.

**Comment by dimitarproynov** [comment]
Fix has been submitted and will be out with the next version.
