### ISSUE TITLE
Defaults should not be set to null - causes SDDC recreation

### ISSUE THREAD

**Issue by jontyq** [vmware/terraform-provider-vmc#94]
For a 1NODE type (possibly for 3 node too, just haven't tested) the settings:
`enable_edrs`
`edrs_policy_type`
`max_hosts`
`min_hosts`

are all optional.  However, if we _don't_ specify them (being optional), we will have the SDDC recreated every time we apply the Terraform.

This is because the API returns values for all of the above settings, which are stored in the state file.  However, the provider tries to set them to `null` every time, because we haven't defined them.

**Expected behaviour**
The default values in the TF state are not changed.

*if* the values differ to what the SDDC has set, that is an open design question - the provider could: 

- attempt to set them back to the default values (assumption that manual configuration has happened and this is correcting the drift)
- Error and not proceed
- Ignore and just accept whatever values come - only attempt to process settings we have actually defined

**Comment by gchek** [comment]
you can  always use
```
lifecycle {     
ignore_changes = [edrs_policy_type, enable_edrs]
}
```

**Comment by jontyq** [comment]
Yeah, roughly the same as having to specify the default values; analysis - lets just fix this :-)

**Comment by dimitarproynov** [comment]
The fix for this bug has been merged. It'll be out with the next release.
